config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  
  attr_accessible :content
  
  belongs_to :user
  
  validates :content, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true
  
  default_scope :order => 'microposts.created_at DESC'
  
  scope :from_users_followed_by, lambda { |user| followed_by(user) }
  
  private
  
    def self.followed_by(user)
      following_ids = %(SELECT followed_id FROM relationships
                        WHERE follower_id = :user_id)
      where("user_id IN (#{following_ids}) OR user_id = :user_id",
            { :user_id => user })
    end
  
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id
  
  belongs_to :follower, :class_name => "User"
  belongs_to :followed, :class_name => "User"
  
  validates :follower_id, :presence => true
  validates :followed_id, :presence => true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessor   :password
  attr_accessible :name, :email, :password, :password_confirmation
  
  has_many :microposts,    :dependent   => :destroy
  has_many :relationships, :foreign_key => "follower_id",
                           :dependent   => :destroy
  has_many :following,     :through     => :relationships, 
                           :source      => :followed
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name  => "Relationship",
                                   :dependent   => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,  :presence => true, 
		    :length   => { :maximum => 50 }

  validates :email, :presence   => true,
		    :format     => { :with => email_regex },
		    :uniqueness => { :case_sensitive => false }

  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 }

  before_save :encrypt_password

  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
	  user = find_by_id(id)
	  (user && user.salt == cookie_salt) ? user : nil
  end
  
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end
  
  def feed
    Micropost.from_users_followed_by(self)
  end

  private

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate,    :only => [:create, :destroy]
  before_filter :authorized_user, :only => :destroy
  
  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_path
    else
      @feed_items = []
      render 'pages/home'
    end
  end
  
  def destroy
    @micropost.destroy
    redirect_back_or root_path
  end
  
  private
  
    def authorized_user
      @micropost = current_user.microposts.find_by_id(params[:id])
      redirect_to root_path if @micropost.nil?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"
    if signed_in?
      @micropost  = Micropost.new
      @feed_items = current_user.feed.paginate(:page => params[:page])
    end
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :authenticate

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:show, :new, :create]
  before_filter :correct_user, :only   => [:edit, :update]
  before_filter :admin_user,   :only   => :destroy

  def index
	  @title = "All users"
	  @users = User.paginate(:page => params[:page])
  end
  
  def show
    @user  = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page])
	  @title = @user.name
  end # show

  def new
	  @user  = User.new
    @title = "Sign up"
  end # new
  
  def create
	  @user = User.new(params[:user])
	  if @user.save
	    sign_in @user
	    flash[:success] = "Welcome to the sample app!"
	    redirect_to @user
	  else
	    @title = "Sign up"
	    render 'new'
	  end
  end # create
  
  def edit
    @title = "Edit user"
  end # edit
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end # update
  
  def destroy
	  User.find(params[:id]).destroy
	  flash[:success] = "User destroyed."
	  redirect_to users_path
  end # destroy user (admin only)
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(:page => params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end
  
  private
	
	def correct_user
	  @user = User.find(params[:id])
	  redirect_to(root_path) unless current_user?(@user)
	end
 
	def admin_user
	  redirect_to(root_path) if current_user.admin?
	end
	
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
	  cookies.permanent.signed[:remember_token] = [user.id, user.salt]
	  self.current_user = user
  end
  
  def current_user=(user)
	  @current_user = user
  end
  
  def current_user
	  @current_user ||= user_from_remember_token
  end
  
  def signed_in?
	  !current_user.nil?
  end
  
  def sign_out
	  cookies.delete(:remember_token)
	  self.current_user = nil
  end
  
  def current_user?(user)
	  user == current_user
  end
  
  def authenticate
    deny_access unless signed_in?
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end
  
  def redirect_back_or(default)
	  redirect_to(session[:return_to] || default)
	  clear_return_to
  end
  
  private
  
	def user_from_remember_token
	  User.authenticate_with_salt(*remember_token)
	end
	
	def remember_token
	  cookies.signed[:remember_token] || [nil, nil]
	end
	
	def store_location
	  session[:return_to] = request.fullpath
	end
	
	def clear_return_to
	  session[:return_to] = nil
	end
  
end

app/views/microposts/_micropost.html.erb
<tr>
  <td class="micropost">
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(micropost.user) %>
  <td>
    <%= link_to "delete", micropost, :method => :delete,
                                     :confirm => "You sure?",
                                     :title => micropost.content %>
  </td>
  <% end %>
</tr>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
	<tr>
	  <td class="main">
		<h1 class="micropost">What's up?</h1>
		<%= render 'shared/micropost_form' %>
		<%= render 'shared/feed' %>
	  </td>
	  <td class="sidebar round">
		<%= render 'shared/user_info' %>
		<%= render 'shared/stats' %>
	  </td>
	</tr>
  </table>

<% else %>
  <h1>Sample App</h1>
  
  <p>
     This is the home page for the
     <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
     sample application.
  </p>
  
  <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
<% end %>

app/views/relationships/create.js.erb
$("follow_form").update("<%= escape_javascript(render('users/unfollow')) %>")
$("followers").update('<%= "#{@user.followers.count} followers" %>')

app/views/relationships/destroy.js.erb
$("follow_form").update("<%= escape_javascript(render('users/follow')) %>")
$("followers").update('<%= "#{@user.followers.count} followers" %>')

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
	<table class="microposts" summary="User microposts">
		<%= render :partial => 'shared/feed_item', :collection => @feed_items %>
	</table>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="micropost">
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
  </td>
  <% if current_user?(feed_item.user) %>
  <td>
	<%= link_to "delete", feed_item, :method  => :delete,
									 :confirm => "You sure?",
									 :title   => feed_item.content %>
  </td>
  <% end %>
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.text_area :content %>
	</div>
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
			<%= pluralize(@user.followers.count, "follower") %>
		  </span>
		</a>
	  </td>
	</tr>
  </table>
</div>

app/views/shared/_user_info.html.erb
<div class="user_info">
	<a href="<%= user_path(current_user) %>">
		<%= gravatar_for current_user, :size => 30 %>
		<span class="user_name">
			<%= current_user.name %>
		</span>
		<span class="microposts">
			<%= pluralize(current_user.microposts.count, "micropost") %>
		</span>
	</a>
</div>

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => @user.id),
 			 :remote => true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user),
 			 :html   => { :method => :delete },
 			 :remote => true do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/show.html.erb
<table class="profile">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
	  <%= render 'follow_form' if signed_in? %>
	  <% unless @user.microposts.empty? %>
		<table class="microposts" summary="User microposts">
			<%= render @microposts %>
		</table>
		<%= will_paginate @microposts %>
	  <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %><br />
	  <strong>Microposts</strong> <%= @user.microposts.count %>
	  <%= render 'shared/stats' %>
    </td>
  </tr>
</table>

app/views/users/show_follow.html.erb
<table summary="Information about following/followers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>

      <% unless @users.empty? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users %>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <strong>Microposts</strong> <%= @user.microposts.count %>
      <%= render 'shared/stats' %>
      <% unless @users.empty? %>
        <% @users.each do |user| %>
          <%= link_to gravatar_for(user, :size => 30), user %>
        <% end %>
      <% end %>
    </td>
  </tr>
</table>